// scripts/afterPack.js — Snippy v1.1.5
// electron-builder afterPack hook: fix Linux sandbox crash for packaged builds.
//
// PROBLEM (two layers on Ubuntu 24.04+):
// 1. chrome-sandbox SUID helper — crashes if not root-owned 4755.
// 2. Namespace sandbox — blocked by AppArmor on Ubuntu 24.04+.
// app.commandLine.appendSwitch('no-sandbox') doesn't help because the
// zygote forks before main.js runs.
//
// FIX:
// 1. Delete chrome-sandbox.
// 2. Rename the real Electron binary -> <name>.bin
// 3. Drop a wrapper script that exec's <name>.bin --no-sandbox "$@"
//
// See: https://github.com/electron-userland/electron-builder/issues/3872

const path = require('path');
const fs = require('fs');

exports.default = async function afterPack(context) {
    // Only relevant on Linux builds
    if (process.platform !== 'linux' && context.packager.platform.name !== 'linux') {
        console.log('[afterPack] Not a Linux build, skipping sandbox workaround.');
        return;
    }

    const appOutDir = context.appOutDir;

    // -----------------------------------------------------------------------
    // Step 1: Remove chrome-sandbox to prevent SUID sandbox crash
    // -----------------------------------------------------------------------
    const chromeSandbox = path.join(appOutDir, 'chrome-sandbox');
    if (fs.existsSync(chromeSandbox)) {
        fs.unlinkSync(chromeSandbox);
        console.log(`[afterPack] Removed ${chromeSandbox}`);
    } else {
        console.log('[afterPack] chrome-sandbox not found, already absent.');
    }

    // -----------------------------------------------------------------------
    // Step 2: Find the actual executable name
    // -----------------------------------------------------------------------
    // On Linux, electron-builder uses the package name (lowercase) as the
    // executable, NOT productName/productFilename. The reliable way to get
    // it is context.packager.executableName.
    const execName = context.packager.executableName;
    const execPath = path.join(appOutDir, execName);
    const realBinary = path.join(appOutDir, `${execName}.bin`);

    console.log(`[afterPack] Looking for executable: ${execPath}`);

    if (!fs.existsSync(execPath)) {
        // Fallback: scan the directory for ELF binaries that aren't chrome-*
        // or lib* to find the actual executable.
        console.error(`[afterPack] ERROR: executable not found at ${execPath}`);
        console.log(`[afterPack] Directory contents: ${fs.readdirSync(appOutDir).join(', ')}`);
        return;
    }

    // -----------------------------------------------------------------------
    // Step 3: Rename binary and create wrapper
    // -----------------------------------------------------------------------
    fs.renameSync(execPath, realBinary);
    console.log(`[afterPack] Renamed ${execPath} -> ${realBinary}`);

    const wrapper = [
        '#!/bin/bash',
        `# Wrapper script generated by afterPack.js — Snippy v1.1.5`,
        '# Launches the real Electron binary with --no-sandbox to bypass both',
        '# the SUID sandbox and the namespace sandbox (blocked by AppArmor on',
        '# Ubuntu 24.04+).',
        '',
        'DIR="$(dirname "$(readlink -f "$0")")"',
        `exec "$DIR/${execName}.bin" --no-sandbox "$@"`,
    ].join('\n');

    fs.writeFileSync(execPath, wrapper, { mode: 0o755 });
    console.log(`[afterPack] Created wrapper script at ${execPath}`);
};
